<a href="https://colab.research.google.com/github/srinikha193/TensorFlow/blob/main/DataC_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
#0D Tensor
d0=tf.ones((1,))

In [3]:
#1D
d1=tf.ones((2,))

In [4]:
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [5]:
print(d1.numpy())

[1. 1.]


In [9]:
#2d
d2=tf.ones((2,2))
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [11]:
#so creating 3d array
d3=tf.ones((2,2,4))
print(d3.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Constants and variables


In [13]:
from tensorflow import constant
#defining 2*3 constant
a=constant(3,shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [17]:
b=constant([1,2,3,4],shape=[1,4])
b

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [27]:
#defining a variable,V casesnetive
a0=tf.Variable([1,2,3,4,5],dtype=tf.float32)
a1=tf.Variable([1,2,3,4,5],dtype=tf.int16)#can't be used becoz only same datatype can be multiplied
#definin g constants
#for addition both tensors shoul dhave same shape
b=tf.constant(2,tf.float32)
#computing the product
c0=tf.multiply(a0,b)
c1=a0*b
print(c1)
print(c0)

tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)
tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)


In [30]:
a=tf.ones([2,3,4])
print(a.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [33]:
b=tf.reduce_sum(a)
b
#summing over dimensions of a
B0=reduce_sum(a,0)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [35]:
#gradients in Ts
#define x
x=tf.Variable(-1.0)
#define y within instance of gradient type
with tf.GradientTape() as tape:
  tape.watch(x)
  y=tf.multiply(x,x)
#evaluate the gradient of y at x=-1
g=tape.gradient(y,x)
print(g.numpy() )

-2.0


In [40]:
#reshaping a grayscale image
gray=tf.random.uniform([2,2,2],maxval=245,dtype=tf.int32)
print(gray.numpy())
gray=tf.reshape(gray,[2*2*2,1])
print(gray.numpy())

[[[100 115]
  [ 54  55]]

 [[150  48]
  [176  28]]]
[[100]
 [115]
 [ 54]
 [ 55]
 [150]
 [ 48]
 [176]
 [ 28]]


In [3]:
import tensorflow as tf

# Define targets and predictions with sample data
targets = tf.constant([1.0, 2.0, 3.0, 4.0])  # Example target values
predictions = tf.constant([1.2, 1.9, 3.1, 3.9])  # Example prediction values

# Calculate the mean squared error
loss = tf.keras.losses.mse(targets, predictions)

# Print the loss
print(loss.numpy())

0.017499996


In [4]:
def linear_regression(intercept, slope = slope, features=features):
  return intercept+features*slope

NameError: name 'slope' is not defined

In [5]:
import tensorflow as tf

# Define targets and predictions with sample data
targets = tf.constant([1.0, 2.0, 3.0, 4.0])  # Example target values
predictions = tf.constant([1.2, 1.9, 3.1, 3.9])  # Example prediction values

# Calculate the mean of targets and predictions
mean_targets = tf.reduce_mean(targets)
mean_predictions = tf.reduce_mean(predictions)

# Calculate the slope using the formula:
# slope = sum((x_i - mean(x)) * (y_i - mean(y))) / sum((x_i - mean(x))^2)
# where x_i are predictions and y_i are targets
numerator = tf.reduce_sum((predictions - mean_predictions) * (targets - mean_targets))
denominator = tf.reduce_sum(tf.square(predictions - mean_predictions))

slope = numerator / denominator

# Now you can use this 'slope' value in your linear_regression function
def linear_regression(intercept, slope=slope, features=None):
  """
  Calculates a linear regression.

  Args:
    intercept: The intercept of the line.
    slope: The slope of the line. Defaults to the calculated slope.
    features: The features to use in the regression. Defaults to None.

  Returns:
    The result of the linear regression.
  """
  if features is None:
    raise ValueError("'features' must be provided if not set as a default argument.")
  return intercept + features * slope

# Example usage:
my_intercept = 2
my_features = 5

result = linear_regression(my_intercept, features=my_features)  # Using the calculated slope
print(result.numpy())

7.323411


In [6]:
# Import the keras module from tensorflow
from tensorflow import keras


In [1]:


import tensorflow as tf

# Create a sample input tensor
input_tensor = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Create a Dropout layer with a rate of 0.5
dropout_layer = tf.keras.layers.Dropout(0.5)

# Apply the dropout layer to the input tensor during training
output_tensor = dropout_layer(input_tensor, training=True)

# Print the output tensor
print(output_tensor.numpy())


[[0. 4. 6.]
 [8. 0. 0.]]
