<a href="https://colab.research.google.com/github/srinikha193/TensorFlow/blob/main/DataC_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
#0D Tensor
d0=tf.ones((1,))

In [3]:
#1D
d1=tf.ones((2,))

In [4]:
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [5]:
print(d1.numpy())

[1. 1.]


In [9]:
#2d
d2=tf.ones((2,2))
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [11]:
#so creating 3d array
d3=tf.ones((2,2,4))
print(d3.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Constants and variables


In [13]:
from tensorflow import constant
#defining 2*3 constant
a=constant(3,shape=[2,3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [17]:
b=constant([1,2,3,4],shape=[1,4])
b

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [27]:
#defining a variable,V casesnetive
a0=tf.Variable([1,2,3,4,5],dtype=tf.float32)
a1=tf.Variable([1,2,3,4,5],dtype=tf.int16)#can't be used becoz only same datatype can be multiplied
#definin g constants
#for addition both tensors shoul dhave same shape
b=tf.constant(2,tf.float32)
#computing the product
c0=tf.multiply(a0,b)
c1=a0*b
print(c1)
print(c0)

tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)
tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)


In [30]:
a=tf.ones([2,3,4])
print(a.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [33]:
b=tf.reduce_sum(a)
b
#summing over dimensions of a
B0=reduce_sum(a,0)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>